<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  	
  	<title>Adaptive Design Studio - Your site doesn't live on a desk anymore</title>
	<meta name="description" content="We specialize  in building websites that are just as brilliant for mobile as they are for the desktop. Contact us to learn how we can make your website adapt 
to the users need.">
	<meta name="author" content="Jakob Viskum Damgaard">
	
	<meta name="viewport" content="width=device-width">
	
	<link rel="shortcut icon" href="favicon.ico"> <!-- 32x32px; transparency OK -->		 
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="apple-touch-icon-114x114-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="apple-touch-icon-72x72-precomposed.png">
	<link rel="apple-touch-icon-precomposed" href="apple-touch-icon-precomposed.png"> <!-- 48x48px; transparency not OK --> 
    
    <!-- Use Pictos for icons -->
    <link href="//get.pictos.cc/fonts/873/1" rel="stylesheet" type="text/css">
    
    <!-- Uses LESS for for styling document.
		 style.css autogenerated with less.app or winless -->
    <link href="css/style.css" rel="stylesheet" type="text/css">
	
	<!-- Don't forget to set site up: http://google.com/webmasters -->
	<meta name="google-site-verification" content="4PggMzOOlaKfHs8TFgRPXSCLZjFFqntQRjY_2L9UQjk">

	<!-- Dublin Core Metadata : http://dublincore.org/ -->
	<meta name="DC.title" content="Adaptive Design Studio">
	<meta name="DC.subject" content="Design websites for all medias.">
	<meta name="DC.creator" content="Jakob Viskum Damgaard from Adaptive Design Studio.">

    <!-- Use Typekit for fonts -->
    <script>TypekitConfig={kitId:"pdf1koa",scriptTimeout:3000};(function(){var d=document.getElementsByTagName("html")[0];d.className+=" wf-loading";var b=setTimeout(function(){d.className=d.className.replace(/(\s|^)wf-loading(\s|$)/g,"");d.className+=" wf-inactive"},TypekitConfig.scriptTimeout);var a=document.createElement("script");a.src="//use.typekit.com/"+TypekitConfig.kitId+".js";a.type="text/javascript";a.async="true";a.onload=a.onreadystatechange=function(){var f=this.readyState;if(f&&f!="complete"&&f!="loaded"){return}clearTimeout(b);try{Typekit.load(TypekitConfig)}catch(g){}};var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(a,c)})();</script>

    <!-- Modernizr: enables HTML5 elements & feature detects -->
    <script src="lib/js/modernizr.min.js"></script>
    
</head>

<body>
<!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
<div class="wrapper">

<header class="bordered">
	<div id="firm-description">
        <h1>Adaptive Design Studio</h1>
        <p>Your site doesn't live on a stationary desk any longer</p>
    </div>
    <nav>
    	<a href="#cases" class="cases">Cases</a>
    	<a href="#work" class="work">Work</a>
    	<a href="#about" class="about">About</a>
    	<a href="#contact" class="contact">Contact</a>
    </nav>
</header>
<div id="adaptive-design">
	
	<picture id="adaptive-design-figure">
		<source src="img/adaptive-design-figure-4x3.png" />
		<source src="img/adaptive-design-figure-6x5.png" media="screen and (min-width: 480px)" />
		<source src="img/adaptive-design-figure-5x4.png" media="screen and (min-width: 720px)" />
		<source src="img/adaptive-design-figure-8x5.png" media="screen and (min-width: 960px)" />
		<source src="img/adaptive-design-figure-10x7.png" media="screen and (min-width: 1120px)" />
		<!-- Fallback content -->
		<img src="img/adaptive-design-figure-4x3.png" />
	</picture>
	
    <p id="adaptive-design-description"><span class="highlighted">We specialize</span> in building websites that are just as brilliant for mobile as they are for the desktop. Contact us to learn how we can make your website adapt to the users need.</p>
    <a href="#get-started" id="get-started" class="btn iconic bars_alt">Get started</a>
</div>

<article id="cases">
    <div class="bordered">
        <h2>Cases</h2>
    </div>
    <a href="http://psykologviskum.dk" target="_blank" class="case">
    	<picture class="picture" id="psykologviskum">
			<source src="img/cases/psykologviskum-4x8.jpg" />
			<source src="img/cases/psykologviskum-3x8.jpg" media="screen and (min-width: 480px)" />
			<source src="img/cases/psykologviskum-4x8.jpg" media="screen and (min-width: 720px)" />
			<!-- Fallback content -->
			<img src="img/cases/psykologviskum-4x8.jpg" />
		</picture>
    	Psykolog Birgitte Viskum
	</a>
    <a href="http://metteomaibom.dk" target="_blank" class="case">
    	<picture class="picture" id="metteomaibom">
			<source src="img/cases/metteomaibom-4x8.jpg" />
			<source src="img/cases/metteomaibom-3x8.jpg" media="screen and (min-width: 480px)" />
			<source src="img/cases/metteomaibom-4x8.jpg" media="screen and (min-width: 720px)" />
			<!-- Fallback content -->
			<img src="img/cases/metteomaibom-4x8.jpg" />
		</picture>
		Mette O. Maibom</a>
	<a href="http://malereskildsen.dk" target="_blank" class="case">
	    <picture class="picture" id="malereskildsen">
			<source src="img/cases/malereskildsen-4x8.jpg" />
			<source src="img/cases/malereskildsen-3x8.jpg" media="screen and (min-width: 480px)" />
			<source src="img/cases/malereskildsen-4x8.jpg" media="screen and (min-width: 720px)" />
			<!-- Fallback content -->
			<img src="img/cases/malereskildsen-4x8.jpg" />
		</picture>
		Mette O. Maibom</a>
    <a href="#" id="load-more" class="btn">Load more</a>
</article>

<article id="work">
    <div class="bordered">
        <h2>Work</h2>
    </div>
    <div id="adaptive-design-grid" class="works">
    	<h3><a href="/adaptivegridsystem/">Adaptive Design Grid</a></h3>
		<a href="/adaptivegridsystem/"><picture class="picture">
			<source src="img/adaptive-grid-system-4x6.png" />
			<source src="img/adaptive-grid-system-6x6.png" media="screen and (min-width: 480px)" />
			<source src="img/adaptive-grid-system-4x11.png" media="screen and (min-width: 720px)" />
			<source src="img/adaptive-grid-system-5x9.png" media="screen and (min-width: 960px)" />
			<source src="img/adaptive-grid-system-6x9.png" media="screen and (min-width: 1120px)" />
			<!-- Fallback -->
			<img src="img/adaptive-grid-system-4x6.png" />
		</picture></a>
        <div class="text">
            <p><span class="highlighted">Everybody wants <a href="http://www.alistapart.com/articles/responsive-web-design/">responsive webdesign</a></span>, but fluid grids are not a designers best choice. The fixed <a href="http://960.gs/" target="_blank">960 gridsystem</a> has been the ruler for quite some time but the increasing amount of web desices have demanded a more responsive approach.</p>
            <p>The middelroad between fixed gridsystemts and responsive design is adaptive design with numerous fixed grids based on the device width. <a href="/adaptivegridsystem/">Adaptive Grid System</a> is a framework ready fro making adaptive design from small smartphones to huge screens.</p>
        </div>
    </div>
    <div id="responsive-images-polyfill" class="works">
    	<h3><a href="responsiveimagepolyfill/">Responsive Images Polyfill</a></h3>
		<a href="responsiveimagespolyfill/"><picture class="picture">
			<source src="http://placehold.it/296x144/000000/E84C38" />
			<source src="http://placehold.it/456x144/000000/E84C38" media="screen and (min-width: 480px)" />
			<source src="http://placehold.it/296x264/000000/E84C38" media="screen and (min-width: 720px)" />
			<source src="http://placehold.it/376x216/000000/E84C38" media="screen and (min-width: 960px)" />
			<source src="http://placehold.it/456x216/000000/E84C38" media="screen and (min-width: 1120px)" />
			<!-- Fallback -->
			<img src="http://placehold.it/296x144/000000/E84C38" />
		</picture></a>
        <div class="text">
            <p><span class="highlighted">How do we handle images i responsive webdesign?</span> This is a question attracting <a href="https://github.com/filamentgroup/Responsive-Images" target="blank">lots</a> and <a href="http://adaptive-images.com/" target="_blank">lots</a> of attention. There <a href="http://www.alistapart.com/articles/responsive-images-how-they-almost-worked-and-what-we-need/" target="_blank">aren't any really good solutions</a> so far. So what do we do?</p>
            <p>Html5 to the rescue - or is it so. The new <a href="http://dev.w3.org/html5/spec/Overview.html#the-video-element" target="_blank">video tag</a> in html5 have options for editing the src based on media-queries. The old <a href="http://www.w3.org/TR/html401/struct/objects.html#h-13.2" target="_blank">img tag</a> can't handle media queries, so a <a href="http://www.w3.org/community/respimg/" target="_blank">proposal for a new picture tag</a> has been made. Let's embrace that request. <a href="responsiveimagespolyfill/">Responsive Images Polyfill</a> is a javascript polyfill making responsive images possible using the picture tag.</p>
        </div>
    </div>
</article>

<article id="about">
    <div class="bordered">
        <h2>About</h2>
    </div>
    <div class="profile">
    	<h3>Our story</h3>
        <h4>Where it all started</h4>
        <picture class="portrait">
			<source src="img/logo-black-3x8.png" />
			<source src="img/logo-black-4x8.png" media="screen and (min-width: 480px)" />
			<source src="img/logo-black-3x8.png" media="screen and (min-width: 720px)" />
			<source src="img/logo-black-6x14.png" media="screen and (min-width: 960px)" />
			<!-- Fallback content -->
			<img src="img/logo-black-3x8.png" />
		</picture>
        <a href="https://twitter.com/#!/adaptivedesignstudio" target="_blank" class="btn twitter" title="@adaptivedesignstudio"></a>
        <a href="http://linkedin.com" target="_blank" class="btn linkedin" title="Adaptive Design Studio @ LinkedIn"></a>
        <a href="mailto:info@adaptivedesignstudio.com" class="btn email" title="info@adaptivedesignstudio.com"></a>
        <p><span class="highlighted">Pellentesque in turpis pharetra</span> mauris fermentum pharetra. Proin sollicitudin congue purus. Nunc in vestibulum elit.</p>
        <p>Etiam dapibus ornare diam, ac suscipit tortor consequat eleifend. Pellentesque rutrum consectetur nisl nec iaculis.</p>
        <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris semper ipsum id magna molestie eu euismod ipsum porttitor.</p>
    </div>
    <div class="profile">
    	<h3>Jakob Viskum Damgaard</h3>
        <h4>Founder, designer and developer</h4>
        <picture class="portrait">
			<source src="img/jvd-3x8.jpg" />
			<source src="img/jvd-4x8.jpg" media="screen and (min-width: 480px)" />
			<source src="img/jvd-3x8.jpg" media="screen and (min-width: 720px)" />
			<source src="img/jvd-6x14.jpg" media="screen and (min-width: 960px)" />
			<!-- Fallback content -->
			<img src="img/jvd-3x8.jpg" />
		</picture>
        <a href="https://twitter.com/#!/jvdamgaard" target="_blank" class="btn twitter" title="@jvdamgaard"></a>
        <a href="http://www.linkedin.com/profile/view?id=165828189" target="_blank" class="btn linkedin" title="Jakob Viskum Damgaard @ LinkedIn"></a>
        <a href="mailto:jakob@adaptivedesignstudio.com" class="btn email" title="jakob@adaptivedesignstudio.com"></a>
        <p><span class="highlighted">Curabitur quis</span> ultrices sem. Nam at felis sit amet ante volutpat molestie in vehicula purus. Nullam nec orci dui, et bibendum mi. Donec ut porta quam. Mauris tempor nunc vel lectus placerat scelerisque ut eu felis.</p>
        <p>Vivamus in orci nulla, vitae bibendum mauris. Phasellus sollicitudin neque at massa ornare eget pellentesque elit porta. Suspendisse aliquam, ante quis adipiscing tincidunt, sem quam volutpat massa, at ullamcorper est massa sed ante.</p>
    </div>
</article>

<article id="contact">
    <div class="bordered">
        <h2>Contact</h2>
    </div>
    <div id="tagline" class="box">
    	<h3><span class="highlighted">Thanks for looking.</span> We'd love to hear from you.</h3>
    </div>
    <div id="hire-us" class="box">
    	<h3>Let's make business</h3>
        <p>Vivamus in orci nulla, vitae bibendum mauris. Phasellus sollicitudin neque at massa ornare eget pellentesque elit porta. Suspendisse aliquam, ante quis adipiscing tincidunt, sem quam volutpat massa, at ullamcorper est massa sed ante.</p>
        <a href="#get-started" id="contact-get-started" class="btn">Get started</a>
    </div>
    <div id="follow" class="box">
    	<h3>Follow</h3>
        <p>Follow <a href="https://twitter.com/#!/adaptivedesignstudio">@adaptivedesignstudio</a> on Twitter for more about our work and cases. We'd like to share all our knowledge with alle interested, som stay tuned.</p>
    </div>
    <div id="email" class="box">
    	<h3>Email</h3>
        <p>Send an e-mail to <a href="mailto:info@adaptivedesignstudio.com">info@adaptivedesignstudio.com</a> if you have any questions, want to learn more about our work or think we should work together.</p>
    </div>
    <div id="location" class="box">
    	<h3>Location</h3>
        <p>Adaptive Design Studio<br>
		Volden 12, 3<br>
		8000 Aarhus C<br>
		Denmark</p>
    </div>
</article>

<footer>
	<picture id="logo">
		<source src="img/logo-1x.png" />
		<source src="img/logo-2x.png" media="screen and (min-width: 480px)" />
		<source src="img/logo-4x7.png" media="screen and (min-width: 720px)" />
		<source src="img/logo-3x9.png" media="screen and (min-width: 960px)" />
		<!-- Fallback content -->
		<img src="img/logo-1x.png" />
	</picture>
    <p class="text">This site is © Adaptive Design Studio 2012. The site is constructed with <a href="http://html5please.com/" target="_blank">html5</a> and <a href="http://css3please.com/" target="_blank">css3</a> build on <a href="http://html5boilerplate.com/" target="_blank">html5boilerplate</a> and using <a href="http://www.modernizr.com/" target="_blank">Modernizr</a> as feature detection. The typeface used is <a href="https://typekit.com/fonts/ff-dagny-web-pro" target="_blank">FF Dagny</a>, served via Typekit and icons is <a href="http://pictos.cc/" target="_blank">Pictos</a> served via Pictos Server. Javascript powered by <a href="http://jquery.com/" target="_blank">jQuery</a> and CSS by <a href="http://lesscss.org/" target="_blank">LESS</a>.</p>
</footer>

</div>

<!-- Async load -->
<script>
	window._gaq = [['_setAccount','UA-29383798-1'],['_trackPageview'],['_trackPageLoadTime']];
    Modernizr.load({ load: [  
		"lib/js/adaptiveimages.polyfill.min.js", 
		//"//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js",
		//"js/functions.js",
		('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js'
	] });
</script>

<!-- Display grid under development -->
<script>
    Modernizr.load({ load: [  
		"lib/js/grid.min.js"
	] });
</script><!-- -->
	
</body>

</html>

