<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  	
  	<title>Adaptive Design Studio - Your site doesn't live on a desk anymore</title>
	<meta name="description" content="We specialize  in building websites that are just as brilliant for mobile as they are for the desktop. Contact us to learn how we can make your website adapt 
to the users need.">
	<meta name="author" content="Jakob Viskum Damgaard">
	
	<meta name="viewport" content="width=device-width">
	
	<link rel="shortcut icon" href="favicon.ico"> <!-- 32x32px; transparency OK -->		 
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="apple-touch-icon-114x114-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="apple-touch-icon-72x72-precomposed.png">
	<link rel="apple-touch-icon-precomposed" href="apple-touch-icon-precomposed.png"> <!-- 48x48px; transparency not OK --> 
    
    <!-- Use Pictos for icons -->
    <link href="//get.pictos.cc/fonts/873/1" rel="stylesheet" type="text/css">
    
    <!-- Uses LESS for for styling document.
		 style.css autogenerated with less.app or winless -->
    <link href="style/style.css" rel="stylesheet" type="text/css">
	
	<!-- Don't forget to set site up: http://google.com/webmasters -->
	<meta name="google-site-verification" content="">

	<!-- Dublin Core Metadata : http://dublincore.org/ -->
	<meta name="DC.title" content="Adaptive Design Studio">
	<meta name="DC.subject" content="Design websites for all medias.">
	<meta name="DC.creator" content="Jakob Viskum Damgaard from Adaptive Design Studio.">

    <!-- Use Typekit for fonts -->
    <script>TypekitConfig={kitId:"pdf1koa",scriptTimeout:3000};(function(){var d=document.getElementsByTagName("html")[0];d.className+=" wf-loading";var b=setTimeout(function(){d.className=d.className.replace(/(\s|^)wf-loading(\s|$)/g,"");d.className+=" wf-inactive"},TypekitConfig.scriptTimeout);var a=document.createElement("script");a.src="//use.typekit.com/"+TypekitConfig.kitId+".js";a.type="text/javascript";a.async="true";a.onload=a.onreadystatechange=function(){var f=this.readyState;if(f&&f!="complete"&&f!="loaded"){return}clearTimeout(b);try{Typekit.load(TypekitConfig)}catch(g){}};var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(a,c)})();</script>

    <!-- Modernizr: enables HTML5 elements & feature detects -->
    <script src="lib/js/modernizr.min.js"></script>
    
</head>

<body>
<!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
<div class="wrapper">

<header class="bordered">
	<div id="firm-description">
        <h1>Adaptive Design Studio</h1>
        <p>Your site doesn't live on a stationary desk any longer</p>
    </div>
    <nav>
    	<a href="#cases" class="cases">Cases</a>
    	<a href="#work" class="work">Work</a>
    	<a href="#about" class="about">About</a>
    	<a href="#contact" class="contact">Contact</a>
    </nav>
</header>
<div id="adaptive-design">
	
	<picture id="adaptive-design-figure">
		<source src="img/adaptive-design-figure-296x72.png" />
		<source src="img/adaptive-design-figure-456x120.png" media="min-width: 480px" />
		<!-- Fallback content -->
		<img src="img/adaptive-design-figure-296x72.png" />
	</picture>
	
    <p id="adaptive-design-description"><span class="highlighted">We specialize</span> in building websites that are just as brilliant for mobile as they are for the desktop. Contact us to learn how we can make your website adapt to the users need.</p>
    <a href="#get-started" id="get-started" class="btn iconic bars_alt">Get started</a>
</div>

<article id="cases">
    <div class="bordered">
        <h2>Cases</h2>
    </div>
    <a href="http://psykologviskum.dk" target="_blank" class="case">
    	<picture class="picture" id="psykologviskum">
			<source src="img/cases/psykologviskum-284x180.jpg" />
			<source src="img/cases/psykologviskum-204x180.jpg" media="min-width: 480px" />
			<!-- Fallback content -->
			<img src="img/cases/psykologviskum-284x180.jpg" />
		</picture>
    	Psykolog Birgitte Viskum
	</a>
    <a href="http://metteomaibom.dk" target="_blank" class="case">
    	<picture class="picture" id="metteomaibom">
			<source src="img/cases/metteomaibom-284x180.jpg" />
			<source src="img/cases/metteomaibom-204x180.jpg" media="min-width: 480px" />
			<!-- Fallback content -->
			<img src="img/cases/metteomaibom-284x180.jpg" />
		</picture>
		Mette O. Maibom</a>
    <a href="#" id="load-more" class="btn">Load more</a>
</article>

<article id="work">
    <div class="bordered">
        <h2>Work</h2>
    </div>
    <div id="adaptive-design-grid" class="works">
    	<h3>Adaptive Design Grid</h3>
		<picture id="adaptive-design-grid-figure">
			<source src="img/adaptive-grid-system-296x144.png" />
			<source src="img/adaptive-grid-system-456x144.png" media="min-width: 480px" />
			<!-- Fallback -->
			<img src="img/adaptive-grid-system-296x144.png" />
		</picture>
        <div class="text">
            <p><span class="highlighted">Lorem ipsum dolor sit</span>  amet, consectetur adipiscing elit. Sed eu orci eros, sed dapibus arcu. Nulla facilisi. Nulla in neque elit, non cursus eros. Duis feugiat diam quam, in sodales purus. Nullam justo justo, auctor et tincidunt ut, placerat nec turpis. Donec id tortor vel tortor aliquam interdum id ut nulla.</p>
            <p>Vestibulum sed facilisis nibh. Praesent consectetur diam non metus rutrum ac hendrerit leo cursus. Phasellus rutrum, orci sed tincidunt pharetra, risus urna dignissim nisl, a ornare velit orci tristique nisi. Curabitur facilisis libero sed dolor pellentesque nec faucibus metus vehicula.</p>
        </div>
    </div>
</article>

<article id="about">
    <div class="bordered">
        <h2>About</h2>
    </div>
    <div class="profile">
    	<h3>Our story</h3>
        <h4>Where it all started</h4>
        <picture class="portrait">
			<source src="img/logo-black-216x192.png" />
			<source src="img/logo-black-296x192.png" media="min-width: 480px" />
			<!-- Fallback content -->
			<img src="img/logo-black-216x192.pngg" />
		</picture>
        <a href="https://twitter.com/#!/adaptivedesignstudio" target="_blank" class="btn twitter" title="@adaptivedesignstudio"></a>
        <a href="http://linkedin.com" target="_blank" class="btn linkedin" title="Adaptive Design Studio @ LinkedIn"></a>
        <a href="mailto:info@adaptivedesignstudio.com" class="btn email" title="info@adaptivedesignstudio.com"></a>
        <p><span class="highlighted">Pellentesque in turpis pharetra</span> mauris fermentum pharetra. Proin sollicitudin congue purus. Nunc in vestibulum elit.</p>
        <p>Etiam dapibus ornare diam, ac suscipit tortor consequat eleifend. Pellentesque rutrum consectetur nisl nec iaculis.</p>
        <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris semper ipsum id magna molestie eu euismod ipsum porttitor.</p>
    </div>
    <div class="profile">
    	<h3>Jakob Viskum Damgaard</h3>
        <h4>Founder, designer and developer</h4>
        <picture class="portrait">
			<source src="img/jvd-216x192.jpg" />
			<source src="img/jvd-296x192.jpg" media="min-width: 480px" />
			<!-- Fallback content -->
			<img src="img/jvd-216x192.jpg" />
		</picture>
        <a href="https://twitter.com/#!/jvdamgaard" target="_blank" class="btn twitter" title="@jvdamgaard"></a>
        <a href="http://www.linkedin.com/profile/view?id=165828189" target="_blank" class="btn linkedin" title="Jakob Viskum Damgaard @ LinkedIn"></a>
        <a href="mailto:jakob@adaptivedesignstudio.com" class="btn email" title="jakob@adaptivedesignstudio.com"></a>
        <p><span class="highlighted">Curabitur quis</span> ultrices sem. Nam at felis sit amet ante volutpat molestie in vehicula purus. Nullam nec orci dui, et bibendum mi. Donec ut porta quam. Mauris tempor nunc vel lectus placerat scelerisque ut eu felis.</p>
        <p>Vivamus in orci nulla, vitae bibendum mauris. Phasellus sollicitudin neque at massa ornare eget pellentesque elit porta. Suspendisse aliquam, ante quis adipiscing tincidunt, sem quam volutpat massa, at ullamcorper est massa sed ante.</p>
    </div>
</article>

<article id="contact">
    <div class="bordered">
        <h2>Contact</h2>
    </div>
    <div id="tagline" class="box">
    	<h3><span class="highlighted">Thanks for looking.</span> We'd love to hear from you.</h3>
    </div>
    <div id="hire-us" class="box">
    	<h3>Let's make business</h3>
        <p>Vivamus in orci nulla, vitae bibendum mauris. Phasellus sollicitudin neque at massa ornare eget pellentesque elit porta. Suspendisse aliquam, ante quis adipiscing tincidunt, sem quam volutpat massa, at ullamcorper est massa sed ante.</p>
        <a href="#get-started" id="contact-get-started" class="btn">Get started</a>
    </div>
    <div id="follow" class="box">
    	<h3>Follow</h3>
        <p>Follow <a href="https://twitter.com/#!/adaptivedesignstudio">@adaptivedesignstudio</a> on Twitter for more about our work and cases. We'd like to share all our knowledge with alle interested, som stay tuned.</p>
    </div>
    <div id="email" class="box">
    	<h3>Email</h3>
        <p>Send an e-mail to <a href="mailto:info@adaptivedesignstudio.com">info@adaptivedesignstudio.com</a> if you have any questions, want to learn more about our work or think we should work together.</p>
    </div>
    <div id="location" class="box">
    	<h3>Location</h3>
        <p>Adaptive Design Studio<br>
		Volden 12, 3<br>
		8000 Aarhus C<br>
		Denmark</p>
    </div>
</article>

<footer>
	<picture id="logo">
		<source src="img/logo-56x56.png" />
		<source src="img/logo-136x136.png" media="min-width: 480px" />
		<!-- Fallback content -->
		<img src="img/logo-56x56.png" />
	</picture>
	<figure class="sprite-adaptive logo"></figure>
    <p class="text">This site is © Adaptive Design Studio 2012 and all our work is  licensed under <a href="#">MIT</a>. The typeface used is <a href="#">FF Dagny</a>, served via Typekit. Javascript powered by <a href="#">jQuery</a>, CSS by <a href="#">LESS</a> and CMS by <a href="#">ProcessWire</a>.</p>
</footer>

</div>

<!-- Async load -->
<script>
	window._gaq = [['_setAccount','UA-29383798-1'],['_trackPageview'],['_trackPageLoadTime']];
    Modernizr.load({ load: [ 
		"//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js", 
		"lib/js/adaptiveimages.polyfill.min.js", 
		"js/functions.js",
		('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js'
	] });
</script>

<!-- Display grid under development -->
<script>
    Modernizr.load({ load: [  
		"lib/js/grid.min.js"
	] });
</script><!-- -->
	
</body>

</html>

