<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  	
  	<title>Responsive Image Polyfill - Tagline</title>
	<meta name="description" content="Description...">
	<meta name="author" content="Jakob Viskum Damgaard">
	
	<meta name="viewport" content="width=device-width">
	
	<link rel="shortcut icon" href="../favicon.ico"> <!-- 32x32px; transparency OK -->		 
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="../apple-touch-icon-114x114-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="../apple-touch-icon-72x72-precomposed.png">
	<link rel="apple-touch-icon-precomposed" href="../apple-touch-icon-precomposed.png"> <!-- 48x48px; transparency not OK --> 
    
    <!-- Use Pictos for icons -->
    <link href="//get.pictos.cc/fonts/873/1" rel="stylesheet" type="text/css">
    
    <!-- Uses LESS for for styling document.
		 style.css autogenerated with less.app or winless -->
    <link href="../css/style.css" rel="stylesheet" type="text/css">
	
	<!-- Don't forget to set site up: http://google.com/webmasters -->
	<meta name="google-site-verification" content="4PggMzOOlaKfHs8TFgRPXSCLZjFFqntQRjY_2L9UQjk">

	<!-- Dublin Core Metadata : http://dublincore.org/ -->
	<meta name="DC.title" content="Responsive Image Polyfill">
	<meta name="DC.subject" content="Subject">
	<meta name="DC.creator" content="Jakob Viskum Damgaard from Adaptive Design Studio.">

    <!-- Modernizr: enables HTML5 elements & feature detects -->
    <script src="../lib/js/modernizr.min.js"></script>

    <!-- Use Typekit for fonts -->
    <script>TypekitConfig={kitId:"pdf1koa",scriptTimeout:3000};(function(){var d=document.getElementsByTagName("html")[0];d.className+=" wf-loading";var b=setTimeout(function(){d.className=d.className.replace(/(\s|^)wf-loading(\s|$)/g,"");d.className+=" wf-inactive"},TypekitConfig.scriptTimeout);var a=document.createElement("script");a.src="//use.typekit.com/"+TypekitConfig.kitId+".js";a.type="text/javascript";a.async="true";a.onload=a.onreadystatechange=function(){var f=this.readyState;if(f&&f!="complete"&&f!="loaded"){return}clearTimeout(b);try{Typekit.load(TypekitConfig)}catch(g){}};var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(a,c)})();</script>
    
</head>

<body>
<!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
<div class="wrapper">

	<picture>
		<source src="http://placehold.it/320x100" />
		<source src="http://placehold.it/480x100" media="screen and (min-width: 480px)" />
		<source src="http://placehold.it/720x100" media="screen and (min-width: 720px)" />
		<source src="http://placehold.it/960x100" media="screen and (min-width: 960px)" />
		<source src="http://placehold.it/1120x100" media="screen and (min-width: 1120px)" />
		<source src="http://placehold.it/1840x100" media="screen and (min-width: 1840px)" />
		<!-- Fallback -->
		<img src="http://placehold.it/320x100" />
	</picture>
	
	<div id="test"></div>

</div>

<!-- Async load -->
<script>
	window._gaq = [['_setAccount','UA-29383798-1'],['_trackPageview'],['_trackPageLoadTime']];
    Modernizr.load({ load: [
		//"../lib/js/adaptiveimages.polyfill.min.js",   
		"//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js",
		"js/functions.js",
		('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js'
	] });
</script>
	
</body>

</html>

